"""Recursos lingüísticos en español para el módulo NLP.

Separar los datos lingüísticos de la lógica permite ampliar el vocabulario
sin tocar los algoritmos. Todas las claves están **sin acentos y en
minúscula**, porque el analizador normaliza el texto antes de buscarlas.

Las claves multipalabra se emparejan primero (coincidencia más larga), lo que
permite resolver casos donde una palabra suelta significaría lo contrario:
``sin peso`` es negativo aunque ``peso`` no tenga polaridad propia.
"""

from app.models.enums import Aspect

# ---------------------------------------------------------------------------
# Léxico de polaridad. Valores en [-1, 1].
# ---------------------------------------------------------------------------

SENTIMENT_LEXICON: dict[str, float] = {
    # --- Positivos ---
    "obra de arte": 1.0,
    "obra maestra": 1.0,
    "vale cada peso": 0.95,
    "vale la pena": 0.8,
    "de lo mejor": 0.85,
    "casi inexistentes": 0.6,
    "compra obligada": 0.8,
    "joya": 0.95,
    "magnifico": 0.95,
    "magnifica": 0.95,
    "excelente": 0.9,
    "impecable": 0.9,
    "impecables": 0.9,
    "deslumbrante": 0.9,
    "espectacular": 0.9,
    "espectaculares": 0.9,
    "delicia": 0.9,
    "maravilla": 0.9,
    "genial": 0.85,
    "increible": 0.85,
    "brillante": 0.85,
    "impresionante": 0.85,
    "buenisimo": 0.9,
    "perfecto": 0.8,
    "perfecta": 0.8,
    "admirable": 0.8,
    "hermoso": 0.8,
    "hermosa": 0.8,
    "adictivo": 0.8,
    "adictiva": 0.8,
    "riquisima": 0.8,
    "riquisimo": 0.8,
    "recomendado": 0.8,
    "altisimo": 0.7,
    "bello": 0.7,
    "memorable": 0.7,
    "emocionante": 0.7,
    "divertido": 0.7,
    "ingenioso": 0.7,
    "satisfactorio": 0.7,
    "preciso": 0.7,
    "precisa": 0.7,
    "pulido": 0.7,
    "engancha": 0.7,
    "enganchado": 0.7,
    "enganchadisimo": 0.9,
    "atrapo": 0.7,
    "disfrute": 0.7,
    "recomiendo": 0.7,
    "mejores": 0.7,
    "creible": 0.6,
    "creibles": 0.6,
    "fluido": 0.6,
    "fluida": 0.6,
    "fluidas": 0.6,
    "balanceada": 0.6,
    "balanceado": 0.6,
    "solido": 0.6,
    "solida": 0.6,
    "obligada": 0.6,
    "mejor": 0.6,
    "supero": 0.6,
    "precision": 0.6,
    "entretenido": 0.55,
    "bueno": 0.5,
    "buena": 0.5,
    "variedad": 0.5,
    "profundidad": 0.5,
    "dosificada": 0.5,
    "estable": 0.5,
    "estables": 0.5,
    "liviano": 0.5,
    "mejoraron": 0.5,
    "recomendaria": 0.7,
    "natural": 0.4,
    "naturales": 0.4,
    "personalidad": 0.4,
    "gusto": 0.4,
    "cuidado": 0.4,
    "carino": 0.3,
    "recomendable": 0.3,
    "exigente": 0.3,
    "justa": 0.3,
    "justo": 0.3,
    # Términos tibios. En el registro de las reseñas "correcto" o "cumple"
    # significan "apenas pasable", no un elogio: con peso alto arrastraban las
    # reseñas neutras hacia la clase positiva.
    "bien": 0.15,
    "correcto": 0.1,
    "correcta": 0.1,
    "decente": 0.1,
    "decentes": 0.1,
    "aceptable": 0.1,
    "cumple": 0.1,
    "acompana": 0.1,
    # Casi nulos, pero necesarios: son la única carga evaluativa de frases como
    # "la trama es sencilla". Sin ellos la regla de "mencionar no es opinar"
    # descarta el aspecto por falta de evidencia sentimental.
    "sencillo": 0.05,
    "sencilla": 0.05,
    "simple": 0.05,
    # Afirmar que algo "tiene peso narrativo" es un elogio.
    "peso narrativo": 0.45,
    "impresionar": 0.3,
    # --- Negativos ---
    "lo poco que": -0.4,
    "rutinario": -0.4,
    "rutinaria": -0.4,
    "falta de respeto": -0.95,
    "no recomiendo": -0.9,
    "dificil de recomendar": -0.8,
    "cabos sueltos": -0.6,
    "sin sentido": -0.7,
    "sin vida": -0.7,
    "sin peso": -0.7,
    "mal explicadas": -0.7,
    "poco responsivos": -0.75,
    "no logre empatizar": -0.7,
    "perdi progreso": -0.7,
    "mucho ruido": -0.6,
    "lejos de": -0.5,
    "en contra": -0.5,
    "no ayuda": -0.6,
    "desastre": -0.95,
    "pesimo": -0.9,
    "pesima": -0.9,
    "pesimamente": -0.9,
    "horrible": -0.9,
    "terrible": -0.9,
    "insufrible": -0.9,
    "decepcion": -0.9,
    "decepcionante": -0.85,
    "flojisimo": -0.85,
    "arruina": -0.85,
    "crashea": -0.8,
    "crasheo": -0.8,
    "crasheos": -0.8,
    "plagado": -0.8,
    "torpe": -0.7,
    "torpes": -0.7,
    "tedioso": -0.7,
    "tediosa": -0.7,
    "aburrido": -0.7,
    "pobre": -0.7,
    "perezoso": -0.7,
    "perezosa": -0.7,
    "flojo": -0.7,
    "desinfla": -0.7,
    "malo": -0.7,
    "mala": -0.7,
    "peor": -0.7,
    "stuttering": -0.7,
    "stutter": -0.7,
    "bugs": -0.65,
    "bug": -0.6,
    "tiron": -0.6,
    "tirones": -0.6,
    "repetitivo": -0.6,
    "repetitiva": -0.6,
    "injusto": -0.6,
    "injustos": -0.6,
    "desactualizado": -0.6,
    "desactualizados": -0.6,
    "vacio": -0.6,
    "vacios": -0.6,
    "acartonado": -0.6,
    "acartonadas": -0.6,
    "generico": -0.6,
    "genericos": -0.6,
    "popping": -0.6,
    "predecible": -0.6,
    "apresurado": -0.6,
    "excusa": -0.6,
    "eterno": -0.6,
    "eternos": -0.6,
    "frustrante": -0.6,
    "fallas": -0.6,
    "mal": -0.6,
    "borroso": -0.5,
    "borrosas": -0.5,
    "plano": -0.5,
    "planos": -0.5,
    "artificial": -0.5,
    "artificiales": -0.5,
    "rompen": -0.5,
    "problema": -0.5,
    "error": -0.5,
    "problemas": -0.55,
    "errores": -0.55,
    "molesta": -0.4,
    "estorbar": -0.4,
    "falta": -0.35,
}

# ---------------------------------------------------------------------------
# Modificadores
# ---------------------------------------------------------------------------

# Invierten la polaridad de las palabras que los siguen.
NEGATORS: frozenset[str] = frozenset(
    {"no", "ni", "nunca", "jamas", "sin", "tampoco", "nada", "ningun", "ninguna", "ninguno"}
)
NEGATION_WINDOW = 4

# "sin embargo" es un conector adversativo, no una negación.
NEGATION_EXCEPTIONS: frozenset[str] = frozenset({"sin embargo"})

INTENSIFIERS: dict[str, float] = {
    "muy": 1.5,
    "muchisimo": 1.8,
    "muchisimos": 1.6,
    "muchisima": 1.8,
    "completamente": 1.6,
    "totalmente": 1.6,
    "absolutamente": 1.7,
    "realmente": 1.3,
    "sumamente": 1.6,
    "extremadamente": 1.7,
    "increiblemente": 1.6,
    "tremendamente": 1.7,
    "brutal": 1.5,
    "bastante": 1.2,
    "constante": 1.3,
    "constantes": 1.3,
    # Amplifican el término al que acompañan en lugar de aportar polaridad
    # propia: "decepción enorme" es más negativo, no menos.
    "enorme": 1.4,
    "tremendo": 1.5,
    "tremenda": 1.5,
    "profunda": 1.3,
    "permanente": 1.3,
}

DIMINISHERS: dict[str, float] = {
    "algo": 0.6,
    "un poco": 0.6,
    "apenas": 0.5,
    "medio": 0.7,
    "ligeramente": 0.5,
    "casi": 0.8,
    "mas o menos": 0.5,
    # "bugs menores" no es lo mismo que "bugs": el adjetivo atenúa el término
    # al que acompaña, igual que "aislado" o "puntual".
    "menor": 0.5,
    "menores": 0.5,
    "aislado": 0.5,
    "aislados": 0.5,
    "puntual": 0.5,
    "puntuales": 0.5,
}

# Marcan un cambio de opinión: se usan para cortar el texto en cláusulas, de
# modo que "los gráficos son lindos pero corre mal" no promedie ambas partes.
CONTRASTIVE_MARKERS: tuple[str, ...] = (
    "sin embargo",
    "si bien",
    "aunque",
    "pero",
    "no obstante",
    "eso si",
)

# ---------------------------------------------------------------------------
# Vocabulario de aspectos (ABSA)
# ---------------------------------------------------------------------------

# Cada término tiene un peso que refleja qué tan discriminante es del aspecto.
# Los términos "débiles" (peso < 0.5) sólo se tienen en cuenta si en la misma
# cláusula no apareció ningún término fuerte: "las mecánicas funcionan bien"
# habla de jugabilidad, no de rendimiento, aunque contenga "funcionan".
ASPECT_TERMS: dict[Aspect, dict[str, float]] = {
    Aspect.GAMEPLAY: {
        "jugabilidad": 1.0,
        "gameplay": 1.0,
        "sistema de combate": 1.0,
        "sistema de progresion": 1.0,
        "diseno de misiones": 1.0,
        "diseno de niveles": 0.9,
        "curva de dificultad": 1.0,
        "bucle de juego": 1.0,
        "mecanica": 0.9,
        "mecanicas": 0.9,
        "combate": 0.9,
        "controles": 0.9,
        "control": 0.7,
        "dificultad": 0.8,
        "farmear": 0.8,
        "tutorial": 0.7,
        "camara": 0.7,
        "manejo": 0.6,
        "movimiento": 0.6,
        "progresion": 0.6,
        "habilidad": 0.5,
        "habilidades": 0.5,
        "mando": 0.5,
        "armas": 0.5,
        "arma": 0.5,
        "bucle": 0.4,
        "jugar": 0.2,
    },
    Aspect.GRAPHICS: {
        "direccion artistica": 1.0,
        "apartado visual": 1.0,
        "diseno de personajes": 1.0,
        "diseno artistico": 1.0,
        "graficamente": 1.0,
        "graficos": 1.0,
        "grafico": 0.9,
        "animaciones": 0.9,
        "animacion": 0.9,
        "iluminacion": 0.9,
        "particulas": 0.9,
        "popping": 0.9,
        "estetica": 0.8,
        "texturas": 0.8,
        "visualmente": 0.9,
        "visual": 0.7,
        "escenarios": 0.6,
        "escenario": 0.5,
        "capturas": 0.5,
        "arte": 0.4,
        "dibujado": 0.4,
    },
    Aspect.STORY: {
        "misiones secundarias": 1.0,
        "construccion del mundo": 1.0,
        "desarrollo emocional": 1.0,
        "peso narrativo": 1.0,
        "narrativa": 1.0,
        "narrativo": 0.9,
        "historia": 1.0,
        "guion": 1.0,
        "trama": 1.0,
        "argumento": 0.9,
        "relato": 0.9,
        "dialogos": 0.9,
        "dialogo": 0.8,
        "personajes": 0.8,
        "protagonistas": 0.8,
        "protagonista": 0.8,
        "giros": 0.7,
        "final": 0.6,
        "escritos": 0.5,
        "revelacion": 0.5,
        "revelaciones": 0.5,
    },
    Aspect.PERFORMANCE: {
        "tiempos de carga": 1.0,
        "cuadros por segundo": 1.0,
        "estado tecnico": 1.0,
        "optimizacion": 1.0,
        "optimizado": 1.0,
        "rendimiento": 1.0,
        "stuttering": 1.0,
        "stutter": 1.0,
        "framerate": 1.0,
        "crashea": 1.0,
        "crasheo": 1.0,
        "crasheos": 1.0,
        "tirones": 1.0,
        "tiron": 0.9,
        "bugs": 0.9,
        "bug": 0.8,
        "fps": 0.9,
        "parches": 0.8,
        "parche": 0.7,
        "tecnicamente": 0.8,
        "tecnico": 0.6,
        "cuadros": 0.6,
        "estabilidad": 0.6,
        # Débiles: sólo cuentan si la cláusula no menciona otro aspecto.
        "corre": 0.4,
        "funciona": 0.3,
        "funcionan": 0.3,
        "carga": 0.3,
        "cargan": 0.3,
        "recursos": 0.4,
        "pulido": 0.3,
    },
}

STRONG_TERM_THRESHOLD = 0.5

# Palabras vacías del español, para el vectorizador TF-IDF del recomendador.
SPANISH_STOPWORDS: list[str] = [
    "a", "al", "algo", "algunas", "algunos", "ante", "antes", "aqui", "asi", "aun",
    "cada", "como", "con", "contra", "cual", "cuando", "de", "del", "desde", "donde",
    "dos", "e", "el", "ella", "ellos", "en", "entre", "es", "esa", "ese", "eso",
    "esta", "estas", "este", "esto", "estos", "fue", "hace", "hacia", "hasta", "hay",
    "la", "las", "le", "les", "lo", "los", "mas", "me", "mi", "mientras", "mismo",
    "mucho", "muchos", "muy", "nada", "ni", "no", "nos", "o", "otra", "otras", "otro",
    "otros", "para", "pero", "poco", "por", "porque", "puede", "pueden", "que",
    "quien", "quienes", "se", "sea", "segun", "ser", "si", "sin", "sobre", "solo",
    "son", "su", "sus", "tambien", "tanto", "tiene", "tienen", "todo", "todos",
    "tras", "tres", "un", "una", "uno", "unos", "y", "ya",
]
