"""esquema inicial completo

Línea base del esquema: users, games, genres, tags, ratings, reviews,
review_aspects, user_preferences, game_lists y game_list_items.

Reemplaza a las dos migraciones anteriores (45cc6ab04725 y 6ace5311065d), que
describían un esquema que ya no existe: la reestructuración del prototipo
cambió nombres de tablas, columnas y relaciones, y encadenar migraciones sobre
aquella base habría dejado una base de datos que no coincide con el ORM. Como
no hay ningún despliegue con datos que preservar, la opción correcta es una
línea base limpia. Las migraciones viejas siguen en el historial de git
(`git show 4ec4e80:backend/alembic/versions/`).

Revision ID: 002fdea0cfa6
Revises:
Create Date: 2026-08-03 16:49:09.664297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002fdea0cfa6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('steam_app_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('released', sa.Date(), nullable=True),
    sa.Column('developer', sa.String(length=120), nullable=True),
    sa.Column('publisher', sa.String(length=120), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('background_image', sa.Text(), nullable=True),
    sa.Column('metacritic', sa.Integer(), nullable=True),
    sa.Column('external_rating', sa.Float(), nullable=True),
    sa.Column('playtime_hours', sa.Integer(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.Column('ratings_count', sa.Integer(), nullable=False),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_avg_rating'), ['avg_rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_developer'), ['developer'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_games_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_ratings_count'), ['ratings_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_released'), ['released'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_games_steam_app_id'), ['steam_app_id'], unique=True)

    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genres_slug'), ['slug'], unique=True)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('steam_id', sa.String(length=20), nullable=True),
    sa.Column('steam_username', sa.String(length=100), nullable=True),
    sa.Column('steam_avatar_url', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('jugador', 'desarrollador', name='userrole', native_enum=False, length=32), nullable=False),
    sa.Column('studio', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_steam_id'), ['steam_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_studio'), ['studio'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('game_genres',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'genre_id')
    )
    op.create_table('game_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('list_type', sa.Enum('favoritos', 'pendientes', 'jugando', 'personalizada', name='listtype', native_enum=False, length=32), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_list_user_name')
    )
    with op.batch_alter_table('game_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_lists_list_type'), ['list_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_lists_user_id'), ['user_id'], unique=False)

    op.create_table('game_tags',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'tag_id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('hours_played', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pendiente', 'jugando', 'completado', 'abandonado', name='gamestatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('score >= 1 AND score <= 5', name='ck_rating_score_range'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', name='uq_rating_user_game')
    )
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ratings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratings_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratings_user_id'), ['user_id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('hours_at_review', sa.Float(), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.Enum('positivo', 'neutro', 'negativo', name='sentiment', native_enum=False, length=32), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_confidence', sa.Float(), nullable=True),
    sa.Column('is_analyzed', sa.Boolean(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', name='uq_review_user_game')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_is_analyzed'), ['is_analyzed'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_sentiment'), ['sentiment'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_user_id'), ['user_id'], unique=False)

    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'genre_id', name='uq_user_genre')
    )
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_preferences_genre_id'), ['genre_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_preferences_user_id'), ['user_id'], unique=False)

    op.create_table('game_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['game_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'game_id', name='uq_list_item')
    )
    with op.batch_alter_table('game_list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_list_items_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_list_items_list_id'), ['list_id'], unique=False)

    op.create_table('review_aspects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('aspect', sa.Enum('jugabilidad', 'graficos', 'historia', 'optimizacion', name='aspect', native_enum=False, length=32), nullable=False),
    sa.Column('sentiment', sa.Enum('positivo', 'neutro', 'negativo', name='sentiment', native_enum=False, length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'aspect', name='uq_review_aspect')
    )
    with op.batch_alter_table('review_aspects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_aspects_aspect'), ['aspect'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_aspects_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_aspects_review_id'), ['review_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_aspects_sentiment'), ['sentiment'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_aspects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_aspects_sentiment'))
        batch_op.drop_index(batch_op.f('ix_review_aspects_review_id'))
        batch_op.drop_index(batch_op.f('ix_review_aspects_game_id'))
        batch_op.drop_index(batch_op.f('ix_review_aspects_aspect'))

    op.drop_table('review_aspects')
    with op.batch_alter_table('game_list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_list_items_list_id'))
        batch_op.drop_index(batch_op.f('ix_game_list_items_game_id'))

    op.drop_table('game_list_items')
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preferences_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_preferences_genre_id'))

    op.drop_table('user_preferences')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_sentiment'))
        batch_op.drop_index(batch_op.f('ix_reviews_is_analyzed'))
        batch_op.drop_index(batch_op.f('ix_reviews_game_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_created_at'))

    op.drop_table('reviews')
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ratings_user_id'))
        batch_op.drop_index(batch_op.f('ix_ratings_game_id'))
        batch_op.drop_index(batch_op.f('ix_ratings_created_at'))

    op.drop_table('ratings')
    op.drop_table('game_tags')
    with op.batch_alter_table('game_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_lists_user_id'))
        batch_op.drop_index(batch_op.f('ix_game_lists_list_type'))

    op.drop_table('game_lists')
    op.drop_table('game_genres')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_studio'))
        batch_op.drop_index(batch_op.f('ix_users_steam_id'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_slug'))

    op.drop_table('tags')
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genres_slug'))

    op.drop_table('genres')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_steam_app_id'))
        batch_op.drop_index(batch_op.f('ix_games_slug'))
        batch_op.drop_index(batch_op.f('ix_games_released'))
        batch_op.drop_index(batch_op.f('ix_games_ratings_count'))
        batch_op.drop_index(batch_op.f('ix_games_name'))
        batch_op.drop_index(batch_op.f('ix_games_external_id'))
        batch_op.drop_index(batch_op.f('ix_games_developer'))
        batch_op.drop_index(batch_op.f('ix_games_avg_rating'))

    op.drop_table('games')
    # ### end Alembic commands ###
