"""agrega popularity_score a games

Revision ID: 26e1ee0668f9
Revises: d8b046a2c9db
Create Date: 2026-08-04 08:10:19.836045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26e1ee0668f9'
down_revision: Union[str, None] = 'd8b046a2c9db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('popularity_score', sa.Float(), nullable=False, server_default='0')
        )
        batch_op.create_index(batch_op.f('ix_games_popularity_score'), ['popularity_score'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_popularity_score'))
        batch_op.drop_column('popularity_score')

    # ### end Alembic commands ###
