"""totales reales de resenas de steam

Revision ID: cfdd581cd83f
Revises: a4f1c9e6d382
Create Date: 2026-08-07 21:24:26.618764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfdd581cd83f'
down_revision: Union[str, None] = 'a4f1c9e6d382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steam_total_reviews', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('steam_positive_reviews', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('steam_positive_reviews')
        batch_op.drop_column('steam_total_reviews')

    # ### end Alembic commands ###
