"""reseñas: user_id opcional, origen y autor

Habilita reseñas importadas de Steam, que no pertenecen a ningún usuario
registrado en GameTrack: ``user_id`` pasa a ser opcional (NULL no choca con
la constraint única `uq_review_user_game`, que sólo compara valores no
nulos), ``source`` distingue "user" de "steam" y ``author_name`` guarda el
nombre a mostrar sin depender de un join con ``users``.

Revision ID: d8b046a2c9db
Revises: 002fdea0cfa6
Create Date: 2026-08-03 20:28:51.682269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8b046a2c9db'
down_revision: Union[str, None] = '002fdea0cfa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=20), server_default='user', nullable=False))
        batch_op.add_column(sa.Column('author_name', sa.String(length=120), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###

    # Backfill: las reseñas ya existentes son de usuarios reales, así que se
    # les completa el nombre a mostrar a partir de `users.username`.
    op.execute(
        """
        UPDATE reviews
        SET author_name = (SELECT username FROM users WHERE users.id = reviews.user_id)
        WHERE author_name IS NULL AND user_id IS NOT NULL
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('author_name')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
